# Generated by Django 6.0.3 on 2026-04-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userprofile_user_code_alter_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('employee', 'พนักงาน'), ('owner', 'เจ้าของ')], default='employee', max_length=20),
        ),
    ]
