# Generated by Django 6.0.3 on 2026-04-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_employee_first_name_employee_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('storefront', 'หน้าร้าน'), ('online', ' онл์ไลน์')], default='storefront', max_length=20),
        ),
    ]
